---
name: Build and test
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add GHC
        uses: actions/setup-haskell@v1.1
        with:
          enable-stack: true
          stack-version: 'latest'
     - run: stack test
